<a href="https://colab.research.google.com/github/semishen/Chinese-NLP-Practices/blob/main/03_CountVectorizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 作業需求
利用以下資料建立詞頻矩陣，並利用詞頻矩陣做量化分析：

1. 將信用卡版討論文章 (https://github.com/ywchiu/tibame_tm/blob/master/data/creditcard_titles.csv) 下載存入到自己電腦
2. 請讀取該檔案，並將所有標題讀入成titles 的list
3. 請使用sklearn 將資料轉換為詞頻矩陣(CountVectorizer)
4. 請使用sklearn 將資料轉換為TF-IDF矩陣(TfidfVectorizer)

In [ ]:
# grab on-line doc 
!wget https://raw.githubusercontent.com/ywchiu/tibame_tm/master/data/creditcard_titles.csv

--2020-07-27 08:56:49--  https://raw.githubusercontent.com/ywchiu/tibame_tm/master/data/creditcard_titles.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3688 (3.6K) [text/plain]
Saving to: ‘creditcard_titles.csv’

creditcard_titles.c 100%[===================>]   3.60K  --.-KB/s    in 0s      

2020-07-27 08:56:49 (51.8 MB/s) - ‘creditcard_titles.csv’ saved [3688/3688]



In [ ]:
# load doc to df
import pandas as pd
import numpy as np

df = pd.read_csv('creditcard_titles.csv', error_bad_lines=False)
df.head()

Unnamed: 0                        title
0           0                 [問題] 富邦j卡新戶禮
1           1  [心得] 玉山 u bear/pi 核卡、台新富邦調額
2           2  Re: [情報] 中信ANA消費應援哩活動(加碼名額)
3           3               [問題] 台新@gogo調額
4           4            [心得] 渣打現金回饋御璽卡 未過

In [ ]:
# df to list

titles = df['title'].to_list()
titles

['[問題] 富邦j卡新戶禮',
 '[心得] 玉山 u bear/pi 核卡、台新富邦調額',
 'Re: [情報] 中信ANA消費應援哩活動(加碼名額)',
 '[問題] 台新@gogo調額',
 '[心得] 渣打現金回饋御璽卡 未過',
 'Re: [閒聊] 本月玉山Only最新抽獎回饋',
 '[情報] 台新也有3倍券 刷50換150 分眾簡訊',
 '[心得] 富邦J卡 星展炫晶 永豐幣倍 國泰Costco 核卡',
 'Re: [情報] 玉山pi分眾屈臣氏促刷活動',
 '[新聞] 為家人上網預購振興券 刷聯邦卡回饋2％',
 '[問題] apple pay算實體刷卡後續疑問',
 '[心得] 神奇的匯豐及渣打新光星展凱基 核卡心得',
 '[心得] 渣打現金回饋御璽卡 核卡（Money101）',
 '[心得] 新光 凱基 新戶核卡',
 '[心得] 渣打現金回饋御璽卡 核卡(money101)',
 '[心得] 中信 LinePay 商務御璽(城市樂跑) 核卡',
 '[問題] 有人信用卡不是用掛號寄來的嗎?',
 '[心得] 渣打現金回饋/富邦J 核卡',
 'Re: [閒聊] 新光悠遊晶緻卡新戶/回饋活動懶人包整理',
 '[問題] 信用卡繳稅後如何付款',
 '[心得] 富邦j卡未核',
 '[心得] 富邦悍將聯名卡核卡',
 '[問題] 申請信用卡的財力證明可以用土地謄本嗎？',
 '[心得] 渣打現金回饋御璽卡 核卡',
 '[心得] 元大鑽金Hello Kitty聯名卡',
 '[心得] 大滿貫之路 匯豐現金 合庫卡娜核卡(18家)',
 'Re: [問題] 請問109年燃料費,有信用卡可回饋嗎?',
 'Re: [情報] 「卡莉嗨」信用卡回饋查詢app',
 '[問題] 玉山wallet 線上繳費疑問',
 '[問題] 聯邦Line Pay Money繳卡費2%',
 '[新聞] 三倍券15日上路 經濟部推數位券、紙本券 ',
 '[心得] 玉山Ubear悠遊聯名卡(黃)高雄Youbike2.0',
 'Re: [心得] U Bear 不佔額度分期回饋',
 '[心得] 渣打現金回饋御璽卡 核卡',
 '[閒聊] 笑死!三倍券綁信用卡最不划算!改換紙本!',
 'Re: [閒聊] 笑死!三倍券綁信用卡最不划算!改換紙本!',
 '[問題

In [ ]:
# word segmentation
import jieba
word_seg_list = []

# name of credit cards (only parts of all)
jieba.add_word('富邦j卡')
jieba.add_word('富邦J')
jieba.add_word('台新GoGo')
jieba.add_word('玉山Pi')
jieba.add_word('玉山pi')
jieba.add_word('玉山ＵBear')
jieba.add_word('@GoGo')
jieba.add_word('台新GOGO')
jieba.add_word('玉山Ubear')
jieba.add_word('兆豐e秒Happy')
jieba.add_word('卡莉嗨')
jieba.add_word('玉山wallet')
jieba.add_word('國泰Costco')
jieba.add_word('聯邦Line')
jieba.add_word('中信ANA')
jieba.add_word('玉山Only')

for sentence in titles:
  word_seg_str = ' '.join(jieba.cut(sentence))
  word_seg_list.append(word_seg_str)
word_seg_list

['[ 問題 ]   富邦j卡 新戶禮',
 '[ 心得 ]   玉山   u   bear / pi   核卡 、 台 新富 邦 調額',
 'Re :   [ 情報 ]   中信ANA 消費 應援哩 活動 ( 加碼 名額 )',
 '[ 問題 ]   台新 @ gogo 調額',
 '[ 心得 ]   渣打 現金 回饋 御璽 卡   未過',
 'Re :   [ 閒聊 ]   本月 玉山Only 最新 抽獎 回饋',
 '[ 情報 ]   台新 也 有 3 倍券   刷 50 換 150   分眾 簡訊',
 '[ 心得 ]   富邦J卡   星展 炫晶   永豐幣 倍   國泰Costco   核卡',
 'Re :   [ 情報 ]   玉山pi 分眾 屈臣氏 促刷 活動',
 '[ 新聞 ]   為 家人 上網 預購 振興券   刷 聯邦卡 回饋 2 ％',
 '[ 問題 ]   apple   pay 算實體 刷卡 後 續 疑問',
 '[ 心得 ]   神奇 的 匯豐及 渣打 新光 星展 凱基   核卡 心得',
 '[ 心得 ]   渣打 現金 回饋 御璽 卡   核卡 （ Money101 ）',
 '[ 心得 ]   新光   凱基   新戶 核卡',
 '[ 心得 ]   渣打 現金 回饋 御璽 卡   核卡 ( money101 )',
 '[ 心得 ]   中信   LinePay   商務御璽 ( 城市 樂跑 )   核卡',
 '[ 問題 ]   有人 信用卡 不是 用 掛號 寄來 的 嗎 ?',
 '[ 心得 ]   渣打 現金 回饋 / 富邦J   核卡',
 'Re :   [ 閒聊 ]   新光 悠遊 晶 緻 卡 新 戶 / 回饋 活動 懶人包 整理',
 '[ 問題 ]   信用卡 繳稅 後 如何 付款',
 '[ 心得 ]   富邦j卡 未核',
 '[ 心得 ]   富邦悍 將聯名 卡 核卡',
 '[ 問題 ]   申請 信用卡 的 財力 證明 可以 用 土地 謄本 嗎 ？',
 '[ 心得 ]   渣打 現金 回饋 御璽 卡   核卡',
 '[ 心得 ]   元大 鑽金 Hello   Kitty 聯名 卡',
 '[ 心得 ]   大滿 貫之路   匯豐 現金   合庫 卡娜 核卡 ( 18 家 )',
 'Re

In [ ]:
# CountVectorizer will drop unrelated some unrelated content
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
result = vectorizer.fit_transform(word_seg_list)
vectorizer.get_feature_names()

['10',
 '109',
 '15',
 '150',
 '18',
 '2020',
 '50',
 'app',
 'apple',
 'bear',
 'gogo',
 'hello',
 'icash',
 'kitty',
 'linepay',
 'money',
 'money101',
 'pay',
 'pi',
 're',
 'ubereat',
 'youbike2',
 '三代',
 '三倍',
 '三越',
 '上市',
 '上網',
 '上路',
 '下半年',
 '不划算',
 '不是',
 '世界',
 '中信',
 '中信ana',
 '中油',
 '付款',
 '位券',
 '使用',
 '促刷',
 '信用卡',
 '倍券',
 '優惠',
 '元大',
 '兆豐e秒happy',
 '全新',
 '凱基',
 '分期',
 '分眾',
 '列入',
 '刷卡',
 '券綁',
 '加碼',
 '助理',
 '匯豐',
 '匯豐及',
 '卡娜',
 '卡換',
 '卡會',
 '卡申',
 '卡莉嗨',
 '卡面',
 '可以',
 '台哥',
 '台新',
 '台新gogo',
 '合庫',
 '名額',
 '售票',
 '商務御璽',
 '商機',
 '問去',
 '問題',
 '嘟嘟',
 '回饋',
 '國旅',
 '國泰',
 '國泰costco',
 '園學費',
 '土地',
 '城市',
 '外幣',
 '多家',
 '大滿',
 '大聯名',
 '太陽',
 '如何',
 '學貸',
 '家人',
 '寄來',
 '富邦',
 '富邦j',
 '富邦j卡',
 '富邦悍',
 '寰宇',
 '將聯名',
 '小白',
 '屈臣氏',
 '年繳',
 '幼兒',
 '張高',
 '影城',
 '御璽',
 '心得',
 '悠遊',
 '情報',
 '感謝',
 '應援哩',
 '懶人包',
 '房停車',
 '折抵',
 '抽獎',
 '拚振興',
 '指定',
 '振新券',
 '振興券',
 '掛號',
 '推數',
 '推薦',
 '推銷',
 '改換',
 '整理',
 '新光',
 '新富',
 '新戶',
 '新戶禮',
 '新聞',
 '星展',
 '最新',
 '有人',
 '未核',
 

In [ ]:
# test result
sample = result.toarray()[10] # 11th title
wordvec_list = vectorizer.get_feature_names()
for i, word in enumerate(wordvec_list):
  if sample[i] != 0:
    print(word)

apple
pay
刷卡
問題
疑問
算實體


In [ ]:
# TfidfVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
tf_idf_vectorizer = TfidfVectorizer()
tf_idf_result = tf_idf_vectorizer.fit_transform(word_seg_list)

In [ ]:
# test result
tf_idf_wordvec_list = tf_idf_vectorizer.get_feature_names()

# keyword in each title
for i,wordvec in enumerate(tf_idf_result.toarray()):
  word_index = np.argmax(wordvec)
  print(f'{tf_idf_wordvec_list[word_index]} | {titles[i]}')


新戶禮 | [問題] 富邦j卡新戶禮
pi | [心得] 玉山 u bear/pi 核卡、台新富邦調額
中信ana | Re: [情報] 中信ANA消費應援哩活動(加碼名額)
gogo | [問題] 台新@gogo調額
未過 | [心得] 渣打現金回饋御璽卡 未過
抽獎 | Re: [閒聊] 本月玉山Only最新抽獎回饋
150 | [情報] 台新也有3倍券 刷50換150 分眾簡訊
國泰costco | [心得] 富邦J卡 星展炫晶 永豐幣倍 國泰Costco 核卡
促刷 | Re: [情報] 玉山pi分眾屈臣氏促刷活動
上網 | [新聞] 為家人上網預購振興券 刷聯邦卡回饋2％
apple | [問題] apple pay算實體刷卡後續疑問
匯豐及 | [心得] 神奇的匯豐及渣打新光星展凱基 核卡心得
money101 | [心得] 渣打現金回饋御璽卡 核卡（Money101）
凱基 | [心得] 新光 凱基 新戶核卡
money101 | [心得] 渣打現金回饋御璽卡 核卡(money101)
中信 | [心得] 中信 LinePay 商務御璽(城市樂跑) 核卡
不是 | [問題] 有人信用卡不是用掛號寄來的嗎?
富邦j | [心得] 渣打現金回饋/富邦J 核卡
懶人包 | Re: [閒聊] 新光悠遊晶緻卡新戶/回饋活動懶人包整理
如何 | [問題] 信用卡繳稅後如何付款
未核 | [心得] 富邦j卡未核
富邦悍 | [心得] 富邦悍將聯名卡核卡
可以 | [問題] 申請信用卡的財力證明可以用土地謄本嗎？
御璽 | [心得] 渣打現金回饋御璽卡 核卡
hello | [心得] 元大鑽金Hello Kitty聯名卡
18 | [心得] 大滿貫之路 匯豐現金 合庫卡娜核卡(18家)
109 | Re: [問題] 請問109年燃料費,有信用卡可回饋嗎?
app | Re: [情報] 「卡莉嗨」信用卡回饋查詢app
玉山wallet | [問題] 玉山wallet 線上繳費疑問
money | [問題] 聯邦Line Pay Money繳卡費2%
15 | [新聞] 三倍券15日上路 經濟部推數位券、紙本券 
youbike2 | [心得] 玉山Ubear悠遊聯名卡(黃)高雄Youbike2.0
分期 | Re: [心得] U Bear 不佔額度分期回饋
御璽 | [

# 詞頻矩陣

In [ ]:
result.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
result.toarray()[10]


array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0])

# TF-IDF矩陣

In [ ]:
tf_idf_result.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
tf_idf_result.toarray()[10]


array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.47122084, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.42953592, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.37701914,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.2115566 , 0.        , 0.        , 0.     